### ISSUE TITLE
ReadQuery shortcut

### ISSUE THREAD

**Issue by zegmaarBasten** [HetBenkt/DQL-Tester-FX#10]
Provide a shortcut for the ‘ReadQuery’ button, for example (shift+enter)
This removes the necessity to use the mouse when writing queries.

**Comment by HetBenkt** [comment]
<F9> will run the first query
<Shift>+<F9> will run the selected query

Separate the queries with a ;
So like this:

```select * from dm_cabinet;
select * from dm_format;```

<F9> will always run in this case `select * from dm_cabinet;`
