### ISSUE TITLE
Does not go past login prompt

### ISSUE THREAD

**Issue by rahulranecool** [HetBenkt/DQL-Tester-FX#14]
Hello,

When I eneter my ID and password on the login prompt, it says in the bottom "Connection to 'docbase' v 0.2 alpha" , but does not actually let me in. So I cannot go ahead and test DQL queries.

Any thoughts?

Thanks,
Rahul

**Comment by lehenry** [comment]
Hello, do you have any logs to share?

**Comment by rahulranecool** [comment]
This was a result of Documentum Data directory not being able to be created.
As a result global registry was not getting published as well.
A simple restart of the machine helped.
