### ISSUE TITLE
Resolution and List of DocBases

### ISSUE THREAD

**Issue by rahulranecool** [HetBenkt/DQL-Tester-FX#15]
Hello,

My desktop is working on its MAX resolution of 1600X900. However I think I am unable to see a few portions ion the bottom of the screen. Could you please take a look at the attached screenshot and let me know if I am missing something - I guess (script execution)? 

Also even though I have 2 docbases (repositories) mentioned in the dfc.properties file, only one comes up in the login screen. I have to comment out the other non needed one for me to get to the one I want to login to.

PS: Unable to attach image files or for that matter word files here
Could you let me know a good email to send these at?

Thanks,
Rahul

**Comment by HetBenkt** [comment]
Hi Rahul,

You can drop me an e-mail at DQLTesterFX@gmail.com with the attachments.
The docbases lest is enhanced in the latest release as we saw the same issues you describe.
Release 0.3 will be available in a couple of weeks, but you can always download and build the package yourself with the latest commits.

Thank you for your comment and feedback.
Best regards,
Antal

**Comment by HetBenkt** [comment]
And you should also be able to able to add attachments by dragging & droping in this edit field. Like this preview sample of the latest release
![2019-08-27_12h04_58](https://user-images.githubusercontent.com/15157563/63762409-033cb980-c8c3-11e9-9ded-8223e4476ab6.png)

**Comment by luke123it** [comment]
Hello,
thank you for your work on this useful tool, and thank you for making it open!

I also experience this issues with release 0.3 on a full-hd screen (1920x1080), in Windows 10, having Fonts zoom set to 125%. See attached screenshot.

![2019-10-07_09-34-52](https://user-images.githubusercontent.com/36679491/66293299-9ddae000-e8e6-11e9-8612-3bee1c2adc47.png)

**Comment by HetBenkt** [comment]
Ok, I see the main screen is fitting...That's good to see!
I just updated the user editor screen so it has the same heigth as the main screen.
The application has now a prefered height of 750 and a prefered width of 800. All the subscreens will be withing this range. Looks like 1920x 1080 with font zoom 125% should be OK with these preferences.
![2019-10-09_09h42_49](https://user-images.githubusercontent.com/15157563/66461475-681a3080-ea79-11e9-9f70-95776027ec74.png)
This will be available in release 0.4
