### ISSUE TITLE
Repository browsing not working

### ISSUE THREAD

**Issue by luke123it** [HetBenkt/DQL-Tester-FX#16]
Hello,

repository browsing doesn't work for me (release 0.3)

When I select Tools -> Browse Repository, nothing happens and an exception is reported in the console window. (see attached file).

[dqleditorfx.log](https://github.com/HetBenkt/DQL-Tester-FX/files/3696016/dqleditorfx.log)

**Comment by HetBenkt** [comment]
Next to your DQLTesterFX-v0.3-alpha.jar file you need have a config directory available. In this directory you will find your `dfc.properties` and you should also have a `settings.properties`  file.

![2019-10-09_09h55_19](https://user-images.githubusercontent.com/15157563/66462227-f4792300-ea7a-11e9-9de7-91355a28381d.png)

In this file you need this content:
```
#
#Mon Jul 08 10:43:33 CEST 2019
browser.allcabinet=true
```

Can you verify that it is available on your side?

**Comment by luke123it** [comment]
Hello
thank for the info. Initially, after putting the settings.properties file in the directory it still wasn't working. But then I realized that I named the directory "conf" instead of "config". After rename it worked properly.
Thanks a lot!

**Comment by HetBenkt** [comment]
Very good...Have fun with the tool!
