### ISSUE TITLE
Opening the Connect dialog for the first time temporarily freezes the application

### ISSUE THREAD

**Issue by jur-clerkx** [HetBenkt/DQL-Tester-FX#17]
It seems that opening the Connect dialog for the first time after starting the application freezes the application for a few seconds. This is most probably caused by the fact that DFC still has to initialize the connection to all the configured Connection Brokers. After this has been initialized for the first time there is no freeze.
It would be perferable to move this the the first Loading screen, so that the application remains more responsive after the loading screen.

**Comment by HetBenkt** [comment]
Hey Jur,

The initializing of DFC is running in a separate thread during startup of the tool. See the [InitRepositoryList](https://github.com/HetBenkt/DQL-Tester-FX/blob/master/src/main/java/nl/bos/InitRepositoryList.java) class which is instantiated in the [MyApplication](https://github.com/HetBenkt/DQL-Tester-FX/blob/master/src/main/java/nl/bos/MyApplication.java) class during initialization.
I agree with you that the loading screen should be longer in place and we continue the rest of the tool _**after**_ the repository list is retrieved...I place it on the backlog...specially for you! :)
