### ISSUE TITLE
Only one docbase is shown in the login screen

### ISSUE THREAD

**Issue by jur-clerkx** [HetBenkt/DQL-Tester-FX#5]
When multiple docbases are available through the configuration of the dfc.properties file, only one repository is shown in the dropdown box in the login screen. Logging shows that multiple docbases have been found, but these are not being shown in the UI.

**Comment by HetBenkt** [comment]
In the code for the Login class I see the below happening. Is it possible to check the log file for the information on the number of repositories found. When multiple repositories are found they should also be available in the repositories combobox/dropdown.

Thx

===============================================================
LOGGER.info(MessageFormat.format("Repositories for Connection Broker: {0}", hostName));
LOGGER.info(MessageFormat.format("Total number of Repositories: {0}", repositoryMap.getDocbaseCount()));

ObservableList<String> repositories = FXCollections.observableArrayList();

for (int i = 0; i < repositoryMap.getDocbaseCount(); i++) {
   LOGGER.info(MessageFormat.format("Repository {0}: {1}", i + 1, repositoryMap.getDocbaseName(i)));
   repositories.add(repositoryMap.getDocbaseName(i));
}

chbRepository.setItems(repositories);
===============================================================

**Comment by HetBenkt** [comment]
Fixed in https://github.com/HetBenkt/DQL-Tester-FX/commit/0d9f86fd901cc9ef93d8ed8de03a6c66321e3fcb
