### ISSUE TITLE
Error notification when querying a non-existing table.

### ISSUE THREAD

**Issue by zegmaarBasten** [HetBenkt/DQL-Tester-FX#9]
Error notification when querying a non-existing table. 
Log info in the attachment.
[error_message.log](https://github.com/HetBenkt/DQL-Tester-FX/files/3367441/error_message.log)

**Comment by HetBenkt** [comment]
When I query at the moment for example `select * from dm_cabinet2;` I get also this error, but that is a logic message as the table is not existing...correct?
Do you also get the pop-up message or do you only see the logging?
And can you continu after the message is click away or is the application hanging?

@zegmaarBasten Please let me know as I think it's not fully clear what you expect to happen.
Thx,
Antal

**Comment by zegmaarBasten** [comment]
The message is logical and correct, at this moment I only see it in the logging and the console. I would prefer to see a pop-up message showing the error instead of having to read it in the logging. 

Normally when I work with DQLtesterFX I minimize the console and have it running on the background meaning I won't see the error message and the query is not running.

**Comment by HetBenkt** [comment]
In the 0.3 it will be a pop-up. I will close the issue for now. Keep in contact if you still see this on the 0.3 release.
